// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhthOs_7FgfTZ8QjxN1iZBrrKX9UhCFsY',
    appId: '1:298596220796:web:7ccff725e55ec442196ef9',
    messagingSenderId: '298596220796',
    projectId: 'flutterproject-884dc',
    authDomain: 'flutterproject-884dc.firebaseapp.com',
    storageBucket: 'flutterproject-884dc.firebasestorage.app',
    measurementId: 'G-1JBP1N53DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmq2fmJsXiS07zjky9z96q-fT6gYa8Kw8',
    appId: '1:298596220796:android:28c3ead717d2687e196ef9',
    messagingSenderId: '298596220796',
    projectId: 'flutterproject-884dc',
    storageBucket: 'flutterproject-884dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMADwmZX8kgzRh2FclMTpjjbqp97WB8Q',
    appId: '1:298596220796:ios:4fe46278c82c6ed4196ef9',
    messagingSenderId: '298596220796',
    projectId: 'flutterproject-884dc',
    storageBucket: 'flutterproject-884dc.firebasestorage.app',
    iosBundleId: 'com.example.shoppingAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhthOs_7FgfTZ8QjxN1iZBrrKX9UhCFsY',
    appId: '1:298596220796:web:4488feef3d89ed04196ef9',
    messagingSenderId: '298596220796',
    projectId: 'flutterproject-884dc',
    authDomain: 'flutterproject-884dc.firebaseapp.com',
    storageBucket: 'flutterproject-884dc.firebasestorage.app',
    measurementId: 'G-MTFFNDBFQR',
  );

}